version: '3.7'
services:
  app:
    build: .
    ports:
      - target: 5000
        published: 80
        protocol: tcp
    environment:
      - AWS_ACCESS_KEY_ID=AccessKeyID
      - AWS_SECRET_ACCESS_KEY=SecretAccessKey
      - AWS_DEFAULT_REGION=eu-west-1
    depends_on:
      - mysql
  mysql:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=group-password
      - MYSQL_DATABASE=groupproject
    volumes:
      - type: volume
        source: mysql-vol
        target: "/var/lib/mysql"
volumes:
  mysql-vol:
